name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Build Project
        run: npm run build
